### ISSUE TITLE
Increase flexibility in API-url replacement

### ISSUE THREAD

**Issue by seriema** [seriema/angular-apimock#16]
Currently `apiMock` simply does a `string.replace` to change `apiPath` into `mockDataPath`.

Two other options could be added:

1. Use a regex for `apiPath`.
1. Use a method for `mockDataPath`.

**Comment by seriema** [comment]
Does anyone really want this or was I just feature-creeping?

**Comment by Wolfium** [comment]
+1,  excellent work, I thought on being backward compatibility being able to handle an array of strings and/or regexs leaving simple string to not get a breaking change.

By the way the only issue I have is only work with true option, don't work if I use auto or number for status code.

**Comment by seriema** [comment]
@Wolfium I created an issue for the bug you reported: #37 Feel free to add any details if you'd like.
