### ISSUE TITLE
add delay configuration

### ISSUE THREAD

**Issue by nadavelyashiv** [seriema/angular-apimock#20]
Hi,

Would be nice to add delay configuration.
(make the mock data returning closer to reality, see some spinners, etc.)

**Comment by seriema** [comment]
Good point! How would you like to set it? There are currently two ways: in the URL with the query parameter `apimock`, or as part of the config object to the `$http` call. Could you give me an example of how you'd like it to work, in both cases?

**Comment by nadavelyashiv** [comment]
I would say something like 
http://server.com/apiprefix?apiMock=true&delay=2000
(In ms)
Or pass in the config object 
{
   delay: 2000
   ...
}

Im sort of new to angular, otherwise i would put in a PR :)
Thanks 
Nadav



‫ב-7 ביוני 2015, בשעה 19:54, ‏‏John-Philip Johansson ‏<notifications@github.com> כתב/ה:‬

**Comment by seriema** [comment]
Right right. Would be best with something unique though, in case `delay` is part of the regular API. Maybe `mockDelay` or `apiMockDelay`?

**Comment by nadavelyashiv** [comment]
Good point.. Sounds great. 



‫ב-7 ביוני 2015, בשעה 23:33, ‏‏John-Philip Johansson ‏<notifications@github.com> כתב/ה:‬

**Comment by luxueyan** [comment]
wait for update

**Comment by seriema** [comment]
@nadavelyashiv and @luxueyan, sorry for the _delay_ ;) but I have it working in a separate branch atm. Feel free to check it out! (see the Github reference message above this post) I'll merge it as soon as #25 is done.

**Comment by seriema** [comment]
@nadavelyashiv and @luxueyan it's merged to main branch now. I haven't published a new version though so to try it you'd need to check the master branch locally, or just manually copy this file: https://github.com/seriema/angular-apimock/blob/8b996d345208e1eed22eebb65cf18bc37d5a7b74/app/scripts/angular-apimock.js

**Comment by nadavelyashiv** [comment]
@seriema Thank you very much, I will check it out!

**Comment by seriema** [comment]
@nadavelyashiv I got a bit anxious to release this and #23 before traveling tomorrow (gone for two weeks). So v0.2.0 is out! Report any bugs in a new issue, but hopefully there won't be any ;D

**Comment by seriema** [comment]
If anyone wants to discuss this feature, I've opened a [Gitter chatroom](https://gitter.im/seriema/angular-apimock).
