### ISSUE TITLE
Handle queries (i.e. "?name=Pikachu")

### ISSUE THREAD

**Issue by seriema** [seriema/angular-apimock#23]
Currently query parameters in the API URL are just stripped out. There should be an optional setting for including them in the redirect.

**Use case**
Better testing of search-like features where one could test search terms that will give different search results, such as no results, a few results, a lot of results, spelling suggestions, etc.

**Usage**
Global flag set in the `config()` by setting `keepQueries` to `true` (default is `false`). Sample:

````
angular.module('testApp', ['apiMock'])
.config(function (apiMockProvider) {
  apiMockProvider.config({
    keepQueries: true
  });
});
````

Local flag set on individual requests, which would be perfect for isolated testing of a autocompletion type search. To not pollute the `$http` config we should scope it within `apiMock`, but that requires another feature (to allow config objects instead of just `true/false`). Sample:

````
app.service('exampleService', function ($http) {
  // ...
  $http({
    method: 'GET',
    url: '...',
    apiMock: {
      keepQueries: true
    }
  }) // ...
  // ...
});
````

**Effect**
Changes redirect logic so that `/api/pokemon?name=Pikachu` no longer strips the query and redirects to `/mock_data/pokemon.get.json`. Instead it redirects to `/mock_data/pokemon_name=pikachu.get.json`.

**Questions**
1. Should it lowercase the queries? Seems like it would be harder to use if it was case sensitive as you'd get `404` when typing `pikachu` instead of `Pikachu`.
2. How to append the query as a file path? Instead of `/mock_data/pokemon_name=pikachu.get.json` an alternative redirect could be `/mock_data/pokemon/name=pikachu.get.json`, which would fit better with #13 (where `/api/pokemon` would redirect to `/mock_data/pokemon/get.json` instead of `/mock_data/pokemon.get.json`).
3. Maybe call it `stripQueries` instead of `keepQueries`? Because its default would be `true`.
4. Should the order of the queries be sorted by alphabet when redirecting? It would decouple the API logic from the static file structure so you wouldn't get `404` because of the order of the queries in the call in comparison to the file names. Example: `/api/pokemon?name=Pikachu&level=1` would redirect to `/mock_data/pokemon/level=1&name=pikachu.get.json` (assuming point 1 was agreed that we'll lowercase everything)..
5. What can we borrow from https://github.com/jeffsaracco/angular-apimock/commit/e11902362cf55671ee92e4466ce143b36d2972ff ?
6. Maybe scope this down to just the global flag and later make an "accept config object in local flags" feature? So we wouldn't have to special-case this.

**Comment by trevcor** [comment]
Still trying to steal some time away to work on this.  Hopefully be done this week.

**Comment by seriema** [comment]
No problem! I'd love to hear your comments on the questions above.

**Comment by trevcor** [comment]
Had some time to look around more of the code and think about your questions.

1.  I agree we should lowercase the query values by default but give a config to override that behavior.  I think the query param name should stay as it is.  Should we call the config forceLowerCaseQueries and default to true?

2.  Yep I like this pattern way better than the underscore.  

3.  Agreed.  Default to true makes more sense.

4.  Yeah this makes sense.

5.  I'm still looking at that commit.  When I view it in github it looks like the entire file was changed so its tough to see what exactly the change was.

6.  I also agree with this.  Let's get the global stuff working and then we can add the targeted api feature later.

So for the global feature we will add 2 config options, forceLowerCaseQueries, stripQueries.

Anything else?

**Comment by seriema** [comment]
1. If the request comes up we can add the flag. I can't find a good use case for mixed casings and it would just add more code/tests unnecessarily. For now let's just have lowercase as default.

5. Yeah it's annoying (hence why I request clean diffs in the contribution guidelines now), but ctrl+f for "appendParamsToPath" and you should see it.

Thanks!

**Comment by seriema** [comment]
If anyone wants to discuss this feature, I've opened a [Gitter chatroom](https://gitter.im/seriema/angular-apimock).
