### ISSUE TITLE
Force mocking

### ISSUE THREAD

**Issue by elhulu** [seriema/angular-apimock#24]
First of all, great work and thank you very much for doing this! 

Would be nice to add a global activation parameter in config. 
something like : 
    apiMockProvider.config({
      mockDataPath: 'tests/',
      apiPath: 'api/',
      forceEnabled : true; // force to serve mocks
    });

In this way i can define a context to serve mocks for all requests (e.g: development) and easily restore normal api responses when i switch to production/staging.

**Comment by seriema** [comment]
That's an excellent idea!

I'm currently focusing on #20 (which is harder to unit-test than I thought), so any PR's are welcome! Take a look at the [contribution guidelines](https://github.com/seriema/angular-apimock/blob/master/CONTRIBUTING.md) if you're up for it.

**Comment by seriema** [comment]
Just realized this would also simplify the unit tests! I'll start on asap.

**Comment by elhulu** [comment]
In fact this is just a forcing of '?apimock=true' parameter. The problem with this parameter is that is not persistent in my app urls, everytime the url change i have to set it again. That's why a global parameter in config would be appropriate. I can try to handle it, i have to explore the code first ;)

**Comment by seriema** [comment]
Yeah, that's annoying and it's been on my Wishlist to figure out how to best persist it between page loads. If we add this to the config object, how do we keep the difference between it and [disable](https://github.com/seriema/angular-apimock#disable) clear? Not a huge thing, but I'd like to keep it simple for users and I personally find similar flags to be confusing on other libraries.

**Comment by Jossbirdly** [comment]
Why not replace 'disable' option by something like 'forceState' = [true/false] ? (true : force enable mocks / false : force disable mocks)
It's solve the problem without needing to change the 'disable' option logic.

**Comment by elhulu** [comment]
Why not replace 'disable' option by something like 'forceState' = [true/false] ? (true : force enable mocks / false : force disable mocks)
It's solve the problem without needing to change the 'disable' option logic.

**Comment by seriema** [comment]
Thinking about it a bit more I find the testability uses the most attractive. Because right now I have to set it on the URL by a mocked `$location` call, which is kinda hackish.

The main idea behind apiMock is to help prototyping and trying things out on different environments without having to touch the code or server. That's why it was built around the URL query. The `disable` option was included as a security measure to stop it from being loaded on a production environment.

So a `force mocking` should still be overridden by local (`$http`) and global (URL) settings. Do you agree?

Then maybe a config option name could be called `default` or `defaultMock` or `defaultCommand`?

**Comment by elhulu** [comment]
I totally agree and the default/defaultMock/defaultCommand/defaultServe option is a good solution.
I understand the original purpose of apiMock, that's why I use it first. 

But sometimes my backend is down or on another version. 
I have all the server mocks as json (for Karma tests).  
The loop can be closed if i can work with every request mocked. Would be a big time saver for me.

ApiMock was probably not made for that. Maybe maybe this can be done with a standalone module, I just thought apiMock was almost ready to do it. 
However, if it's added to apiMock, it can be a good rescue environment, I haven't found any library to do it.

**Comment by seriema** [comment]
Oh, don't get me wrong. I loved the idea. I'm already preparing the code for it =) As soon as #25 is merged I'll include it.

I'd gladly hear more about how you use apiMock, if you can spare the time. My email is seriema at gmail.

**Comment by seriema** [comment]
In addition to this one, I wonder how we could have this behaviour (keeping mock active) between pages. If `$route` was used I guess there's a way to persist `apiMock=true` in `$location`, but that wouldn't help everyone.

Another idea would be to persist in a `sessionStorage` (I think `localStorage` would be too permanent) which would be ok for all browers except Opera Mini ([caniuse](http://caniuse.com/#search=sessionstorage)).

**Comment by elhulu** [comment]
sessionStorage or localStorage :+1:   !
About Opera Mini : sometime you can't please everybody ;)  ( < 5% of market share. Not a great loss for me )

**Comment by Wolfium** [comment]
While I started to use this library I got a simple workaround to the issue that is the following: 

```javascript
    .run( function ($rootScope, $location) {
      $rootScope.$on('$stateChangeStart',
        function () {
          //save location.search so we can add it back after transition is done
        $location.locationSearch = $location.search();
      });

      $rootScope.$on('$stateChangeSuccess',
        function (/*event, toState, toParams, fromState, fromParams*/) {
          //restore all query string parameters back to $location.search
          $location.search($location.locationSearch);
      });
    });
```

I know that it add dependencies and complexity to the client project it works for me for know.
