### ISSUE TITLE
Add a main entry in package.json

### ISSUE THREAD

**Issue by jrmlstfMt** [seriema/angular-apimock#65]
Could you consider to add a `main` field in package.json in order to use `require('angular-apimock)` instead of `require('angular-apimock/dist/angular-apimock.js')`?

https://docs.npmjs.com/files/package.json#main

**Comment by seriema** [comment]
@jrmlstfMt There is one? https://github.com/seriema/angular-apimock/blob/master/package.json#L26 :)
